# Configuration for development teams
language: "ja-JP"

reviews:
profile: "assertive"
high_level_summary: true
auto_review:
enabled: true
drafts: false
ignore_title_keywords:
  - "wip"
  - "draft"
tools:
eslint:
  enabled: true
ruff:
  enabled: true
gitleaks:
  enabled: true
hadolint:
  enabled: true

chat:
auto_reply: true